name: customer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.4
  get_it: ^7.2.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  qr_flutter: ^4.0.0
  flutter_credit_card: ^3.0.4
  google_maps_flutter: ^2.2.1
  package_info_plus: ^1.4.3+1
  geolocator: ^9.0.2
  after_layout: ^1.2.0
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - map.json
