name: customer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  get_it: ^7.2.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  qr_flutter: ^4.0.0
  google_maps_flutter: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
